[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "theLabyrinth"
version = "0.1.0"
description = "Terminal Word Game in Python/Textual"
dependencies = [
    "requests",
    "rich",
    "rich-pixels",
    "textual",
    "pillow",
    "textual-dev>=1.8.0",
]

[project.scripts]
theLabyrinth = "main:main"

[tool.setuptools]
packages = ["screens", "gameLogic", "menuLogic", "styles"]
py-modules = ["main"]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.package-data]
styles = ["*.tcss"]
